version: 2.1
orbs:
  slack: circleci/slack@4.12.1
jobs:
  slack-notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          event: fail
          mentions: '@EngineeringTeam'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

  build-frontend:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
  build-backend:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build
  test-frontend:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Unit testing for FE
          command: |
            cd frontend
            npm install
            npm run test
  test-backend:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Unit testing for BE
          command: |
            cd backend
            npm install
            npm run test
  scan-frontend:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Scanning FE
          command: |
            cd frontend
            npm install
            npm audit --audit-level=critical
  scan-backend:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Scanning BE
          command: |
            cd backend
            npm install
            npm audit --audit-level=critical

workflows:
  default:
    jobs:
      - slack-notify:
          context: global
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - scan-backend:
          requires: [build-backend]
