version: 2.1
orbs:
  slack: circleci/slack@4.12.1
  aws: circleci/aws-cli@3.1.5
  python: circleci/python@2.0.3
commands:
  setup-aws:
    description: setup aws
    steps:
      - aws/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
  destroy-infra-fe:
    description: using for rollback creating fe infra
    parameters:
      id:
        type: string
    steps:
      - run:
          name: delete all aws s3 files
          command: aws s3 rm s3://udapeople-<< parameters.id >> --recursive
          when: on_fail
      - run:
          name: delete frontend stack
          command: aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.id >>
          when: on_fail
  destroy-infra-be:
    description: using for rollback creating be infra
    parameters:
      stack_name:
        type: string
    steps:
      - run:
          name: destroy stack <<parameters.stack_name>>
          command: aws cloudformation delete-stack --stack-name "<<parameters.stack_name>>"
          when: on_fail
  revert-migration:
    description: Revert the migration.
    parameters:
      force_revert:
        type: boolean
        default: false
    steps:
      - run:
          name: Revert migrations
          command: chmod +x backend/runRevertMigration.sh && backend/runRevertMigration.sh << parameters.force_revert >>
          when: always
jobs:
  slack-notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          event: fail
          mentions: '@EngineeringTeam'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

  build-frontend:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
  build-backend:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
            npm run build
  test-frontend:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Unit testing for FE
          command: |
            cd frontend
            npm install
            npm run test
  test-backend:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Unit testing for BE
          command: |
            cd backend
            npm install
            npm run test
  scan-frontend:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Scanning FE
          command: |
            cd frontend
            npm install
            npm audit --audit-level=critical
  scan-backend:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Scanning BE
          command: |
            cd backend
            npm install
            npm audit --audit-level=critical
  deploy-infrastructure-be:
    docker:
      - image: node:14-alpine
    working_directory: ~/project
    steps:
      - checkout
      - setup-aws
      - run:
          name: infrastructure in BE
          command: |
            aws cloudformation deploy \
             --template-file .circleci/files/backend.yml \
               --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
               --tags project=udapeople
      - run:
          name: create inventory
          command: |
            chmod +x .circleci/bash/IPAddress.sh
            echo [web] > .circleci/ansible/inventory.txt
            .circleci/bash/IPAddress.sh "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" >> .circleci/ansible/inventory.txt
      - run: cat .circleci/ansible/inventory.txt
      - save_cache:
          paths:
            - .circleci/ansible/inventory.txt
          key: inventory-{{ .Revision  }}
  deploy-infrastructure-fe:
    docker:
      - image: node:14-alpine
    working_directory: ~/project
    steps:
      - checkout
      - setup_aws
      - run:
          name: infrastructure in FE
          command: |
            aws cloudformation deploy \
             --template-file .circleci/files/frontend.yml \
               --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
               --tags project=udapeople
  configure-infra:
    executor: python/default
    working_directory: ~/project
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 5e:0a:cf:5d:a3:74:92:9a:8b:9f:eb:dc:50:6b:16:75
      - restore_cache:
          key: inventory-{{ .Revision  }}
      - run:
          name: install ansible
          command: pip install --user ansible
      - run:
          name: configure with ansible
          command: ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml
  run-migration:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - restore_cache:
          key: be-caches-{{ checksum "backend/package.json" }}
      - run:
          name: Run migration
          command: |
            cd backend
            npm install
            npm run migrations > migrations_dump.txt
      - run:
          name: send migration status to kvdb
          command: chmod +x .circleci/bash/MigrationResult.sh && .circleci/bash/MigrationResult.sh
      - revert-migration
  deploy-frontend:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Install and setup awscli
          command: chmod +x .circleci/bash/installAndSetupAws.sh && .circleci/bash/installAndSetupAws.sh
      - restore_cache:
          name: restore node_modules
          key: fe-caches-{{ checksum "frontend/package.json" }}
      - restore_cache:
          keys:
            - fe-caches-{{ checksum "frontend/package.json" }}
            - inventory-{{ .Revision  }}
      - run:
          name: export env
          command: |
            export BACKEND_IP=$(cat .circleci/ansible/inventory.txt | tail -n 1)
            export API_URL="http://${BACKEND_IP}:3030"
            echo "API_URL = ${API_URL}"
            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
            cat frontend/.env
      - run:
          name: Build frontend and deploy s3
          command: |
            cd frontend
            npm run build
            tar -czvf artifact-"${TEST_FE_STACK_ID:0:7}".tar.gz dist
            aws s3 cp dist s3://udapeople-${TEST_FE_STACK_ID:0:7} --recursive
  deploy_backend:
    executor: python/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 5e:0a:cf:5d:a3:74:92:9a:8b:9f:eb:dc:50:6b:16:75
      - restore_cache:
          name: restore inventory
          keys:
            - inventory-{{ .Revision  }}
            - inventory-
      - run:
          name: install ansible
          command: pip install --user ansible
      - run:
          name: create artifact
          command: tar -C backend -czvf .circleci/ansible/roles/deploy/artifact/artifact.tar.gz .
      - run:
          name: Start backend with ansible
          command: ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/deploy-backend.yml
  smoke-test:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: install and setup aws
          command: chmod +x .circleci/bash/installAndSetupAws.sh && .circleci/bash/installAndSetupAws.sh
      - restore_cache:
          name: restore inventory
          keys:
            - inventory-{{ .Revision  }}
            - inventory-
      - restore_cache:
          name: restore node_modules
          keys:
            - be-caches-{{ checksum "backend/package.json" }}
      - run:
          name: Back End smoke test
          command: chmod +x .circleci/bash/BESmokeTest.sh && .circleci/bash/BESmokeTest.sh
      - run:
          name: Front End smoke test
          command: chmod +x .circleci/bash/FESmokeTest.sh && .circleci/bash/FESmokeTest.sh $FE_WORKFLOW_TEST_ID
      - revert_migration_when_failed:
          force_revert: true
      - destroy-infra-be:
          stack_name: udapeople-backend-${BE_WORKFLOW_TEST_ID:0:7}
      - destroy-infra-fe:
          id: ${FE_WORKFLOW_TEST_ID:0:7}
workflows:
  default:
    jobs:
      # - slack-notify:
      #     context: global
      # - build-frontend:
      #     context: global
      # - build-backend:
      #     context: global
      # - test-frontend:
      #     requires:
      #       - build-frontend
      # - test-backend:
      #     requires:
      #       - build-backend
      # - scan-frontend:
      #     requires:
      #       - build-frontend
      # - scan-backend:
      #     requires:
      #       - build-backend
      # - deploy-infrastructure-be:
      #     requires:
      #       - build-backend
      #       - test-backend
      #       - scan-backend
      # - deploy-infrastructure-be
      # - deploy_infra_fe
      # - configure-infra:
      #     requires:
      #       - deploy-infrastructure-be
      # - run-migration:
      #     requires:
      #       - build-backend
      # - deploy-frontend:
      #     requires:
      #       - build-frontend
      #       - configure-infra
      # - deploy_backend:
      #     requires:
      #       - configure-infra
      - smoke-test
